<?php

namespace App\Enums;

enum ProcessesCategoryEnum: string
{
    case DIREITO_A_EDUCACAO = 'DIREITO À EDUCAÇÃO';
    case DIREITO_ADMINISTRATIVO = 'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO';
    case DIREITO_AMBIENTAL = 'DIREITO AMBIENTAL';
    case DIREITO_ASSISTENCIAL = 'DIREITO ASSISTENCIAL';
    case DIREITO_CIVIL = 'DIREITO CIVIL';
    case DIREITO_CRIANCA_ADOLESCENTE = 'DIREITO DA CRIANÇA E DO ADOLESCENTE';
    case DIREITO_DA_SAUDE = 'DIREITO DA SAÚDE';
    case DIREITO_DO_CONSUMIDOR = 'DIREITO DO CONSUMIDOR';
    case DIREITO_DO_TRABALHO = 'DIREITO DO TRABALHO';
    case DIREITO_ELEITORAL = 'DIREITO ELEITORAL';
    case DIREITO_ELEITORAL_STF = 'DIREITO ELEITORAL E PROCESSO ELEITORAL DO STF';
    case DIREITO_INTERNACIONAL = 'DIREITO INTERNACIONAL';
    case DIREITO_MARITIMO = 'DIREITO MARÍTIMO';
    case DIREITO_PENAL = 'DIREITO PENAL';
    case DIREITO_PENAL_MILITAR = 'DIREITO PENAL MILITAR';
    case DIREITO_PREVIDENCIARIO = 'DIREITO PREVIDENCIÁRIO';
    case DIREITO_PROCESSUAL_CIVIL_TRABALHO = 'DIREITO PROCESSUAL CIVIL E DO TRABALHO';
    case DIREITO_PROCESSUAL_PENAL = 'DIREITO PROCESSUAL PENAL';
    case DIREITO_PROCESSUAL_PENAL_MILITAR = 'DIREITO PROCESSUAL PENAL MILITAR';
    case DIREITO_TRIBUTARIO = 'DIREITO TRIBUTÁRIO';
    case QUESTOES_GRANDE_IMPACTO = 'QUESTÕES DE ALTA COMPLEXIDADE, GRANDE IMPACTO E REPERCUSSÃO';
    case REGISTROS_PUBLICOS = 'REGISTROS PÚBLICOS';
}
